// Code generated by "enumer -type=Status -json -text -trimprefix=Status -output=status_enumer.go"; DO NOT EDIT.

package enumerdemo

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _StatusName = "PendingActiveInactiveDeleted"

var _StatusIndex = [...]uint8{0, 7, 13, 21, 28}

const _StatusLowerName = "pendingactiveinactivedeleted"

func (i Status) String() string {
	if i < 0 || i >= Status(len(_StatusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return _StatusName[_StatusIndex[i]:_StatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StatusNoOp() {
	var x [1]struct{}
	_ = x[StatusPending-(0)]
	_ = x[StatusActive-(1)]
	_ = x[StatusInactive-(2)]
	_ = x[StatusDeleted-(3)]
}

var _StatusValues = []Status{StatusPending, StatusActive, StatusInactive, StatusDeleted}

var _StatusNameToValueMap = map[string]Status{
	_StatusName[0:7]:        StatusPending,
	_StatusLowerName[0:7]:   StatusPending,
	_StatusName[7:13]:       StatusActive,
	_StatusLowerName[7:13]:  StatusActive,
	_StatusName[13:21]:      StatusInactive,
	_StatusLowerName[13:21]: StatusInactive,
	_StatusName[21:28]:      StatusDeleted,
	_StatusLowerName[21:28]: StatusDeleted,
}

var _StatusNames = []string{
	_StatusName[0:7],
	_StatusName[7:13],
	_StatusName[13:21],
	_StatusName[21:28],
}

// StatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

// StatusValues returns all values of the enum
func StatusValues() []Status {
	return _StatusValues
}

// StatusStrings returns a slice of all String values of the enum
func StatusStrings() []string {
	strs := make([]string, len(_StatusNames))
	copy(strs, _StatusNames)
	return strs
}

// IsAStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Status) IsAStatus() bool {
	for _, v := range _StatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Status
func (i Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Status
func (i *Status) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Status should be a string, got %s", data)
	}

	var err error
	*i, err = StatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Status
func (i Status) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Status
func (i *Status) UnmarshalText(text []byte) error {
	var err error
	*i, err = StatusString(string(text))
	return err
}
