// Code generated by "stringer -type=Color -trimprefix=Color"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorRed-0]
	_ = x[ColorGreen-1]
	_ = x[ColorBlue-2]
	_ = x[ColorYellow-3]
}

const _Color_name = "RedGreenBlueYellow"

var _Color_index = [...]uint8{0, 3, 8, 12, 18}

func (i Color) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Color_index)-1 {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[idx]:_Color_index[idx+1]]
}
