// Code generated by "stringer -type=Weekday -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Monday-1]
	_ = x[Tuesday-2]
	_ = x[Wednesday-3]
	_ = x[Thursday-4]
	_ = x[Friday-5]
	_ = x[Saturday-6]
	_ = x[Sunday-7]
}

const _Weekday_name = "周一周二周三周四周五周六周日"

var _Weekday_index = [...]uint8{0, 6, 12, 18, 24, 30, 36, 42}

func (i Weekday) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Weekday_index)-1 {
		return "Weekday(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Weekday_name[_Weekday_index[idx]:_Weekday_index[idx+1]]
}
