// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiredemo

// Injectors from wire.go:

// InitializeApp 是wire的Injector声明。
// wire会分析所有Provider的输入输出类型，自动生成依赖组装代码。
//
// 这个函数体会被wire生成的代码完全替换。
func InitializeApp(cfg *Config) (*App, error) {
	database, err := NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepo := NewUserRepo(database)
	userService := NewUserService(userRepo)
	app := NewApp(userService, cfg)
	return app, nil
}
