// Code generated by "stringer -type=Scene -linecomment"; DO NOT EDIT.

package simplefactory

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SceneDingDing-1]
	_ = x[SceneWeixin-2]
	_ = x[SceneFeishu-3]
}

const _Scene_name = "dingdingweixinfeishu"

var _Scene_index = [...]uint8{0, 8, 14, 20}

func (i Scene) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Scene_index)-1 {
		return "Scene(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Scene_name[_Scene_index[idx]:_Scene_index[idx+1]]
}
